//{{NO_DEPENDENCIES}}
// ���������� ����, ��������� � Microsoft Visual C++.
// ������������ fileinfo.rc
//
#define IDI_APP                         101
#define IDI_FILEOPEN                    102
#define IDC_OPENFILE                    1001
#define IDC_EDITFILE                    1002
#define IDC_OPENFILE2                   1003
#define IDC_OPENDIRECTORY               1003
#define IDC_BFI_CREATION_TIME_DATE      1010
#define IDC_BFI_CREATION_TIME_TIME      1011
#define IDC_BFI_LAST_ACCESS_TIME_DATE   1012
#define IDC_BFI_LAST_ACCESS_TIME_TIME   1013
#define IDC_BFI_LAST_WRITE_TIME_DATE    1014
#define IDC_BFI_LAST_WRITE_TIME_TIME    1015
#define IDC_BFI_CHANGE_TIME_DATE        1016
#define IDC_BFI_CHANGE_TIME_TIME        1017
#define IDC_ATTRIBUTE_ARCHIVE           1018
#define IDC_ATTRIBUTE_HIDE              1019
#define IDC_ATTRIBUTE_NORMAL            1020
#define IDC_ATTRIBUTE_INDEXED           1021
#define IDC_ATTRIBUTE_OFFLINE           1022
#define IDC_ATTRIBUTE_READONLY          1023
#define IDC_ATTRIBUTE_SYSTEM            1024
#define IDC_ATTRIBUTE_TEMPORARY         1025
#define IDC_ATTRIBUTE_COMPRESSED        1026
#define IDC_ATTRIBUTE_DIRECTORY         1027
#define IDC_ATTRIBUTE_CRYPTED           1028
#define IDC_ATTRIBUTE_SPARSE            1029
#define IDC_CHECK12                     1030
#define IDC_LOCKER                      1031
#define IDC_FILEINFO_SAVE               1032
#define IDC_FILEINFO_RESTORE            1033
#define IDC_INFOTAB                     1034
#define IDC_CREATE_STREAM               1038
#define IDC_BUTTON1                     1039
#define IDC_RESTART_AS_ADMINISTARTOR    1039
#define IDC_VOLUME_SERIAL_NUMBER        1040
#define IDC_FILE_UNIQUE_ID              1041
#define IDC_ALLOCATED_SIZE              1074
#define IDC_ENDOF_FILE                  1075
#define IDC_NUMBER_OF_LINKS             1076
#define IDC_DELETED_PENDING             1077
#define IDC_IS_DIRECTORY                1078
#define IDC_STREAM_LIST                 1079
#define IDM_CREATE_STREAM               1081
#define IDM_VIEW_STREAM                 1082
#define IDC_EXIF_LIST                   1083
#define IDC_EXIF_STATUS                 1084
#define IDM_SAVE_STREAM                 1085
#define IDC_SHELL_INTEGRATE             1086
#define IDM_DELETE_STREAM               1087
#define IDM_COPY_SELECTION              1088
#define IDM_COMPARE_FILE                1089
#define IDC_STREAM_VIEWER_EDIT          1090
#define IDC_STREAM_VIEWER_MODE          1091
#define IDD_STREAM_VIEWER               200
#define ID_RECENT_FILE_BASE             40001

// String table IDs
#define IDS_ERROR_TITLE          2000
#define IDS_ERROR_FORMAT         2001
#define IDS_APP_TITLE            2010
#define IDS_TAB_BASIC            2011
#define IDS_TAB_STANDARD         2012
#define IDS_TAB_STREAMS          2013
#define IDS_TAB_ID               2014
#define IDS_TAB_EXIF             2015
#define IDS_TOOLTIP_OPEN_FILE    2016
#define IDS_TOOLTIP_OPEN_DIR     2017
#define IDS_BROWSE_TITLE         2018
#define IDS_WARN_READONLY_MSG    2019
#define IDS_WARN_READONLY_TITLE  2020
#define IDS_ERR_SECURITY         2021
#define IDS_ERR_SETATTR          2022
#define IDS_ERR_CREATEFILE       2023
#define IDS_ERR_REG_CREATE       2024
#define IDS_ERR_REG_CREATE_CMD   2025
#define IDS_ERR_SETFILEINFO      2026
#define IDS_COL_NUM              2030
#define IDS_COL_NAME             2031
#define IDS_COL_SIZE             2032
#define IDS_COL_ALLOC            2033
#define IDS_STREAM_OPEN_TITLE    2034
#define IDS_STREAM_CONFIRM_FMT   2035
#define IDS_STREAM_CONFIRM_TITLE 2036
#define IDS_STREAM_ERR_SRC_OPEN  2037
#define IDS_STREAM_ERR_DST_OPEN  2038
#define IDS_STREAM_ERR_WRITE     2039
#define IDS_STREAM_WRITE_OK      2040
#define IDS_STREAM_WRITE_OK_TITLE 2041
#define IDS_STREAM_SAVE_TITLE    2042
#define IDS_STREAM_ERR_OPEN      2043
#define IDS_STREAM_ERR_FILE_OPEN 2044
#define IDS_STREAM_ERR_READ      2045
#define IDS_STREAM_SAVE_OK       2046
#define IDS_STREAM_SAVE_OK_TITLE 2047
#define IDS_STREAM_MENU_VIEW     2048
#define IDS_STREAM_MENU_SAVE     2049
#define IDS_STREAM_MENU_CREATE   2050
#define IDS_STREAM_NO_SEL_MSG    2051
#define IDS_STREAM_NO_SEL_TITLE  2052
#define IDS_STREAM_EMPTY_NAME_MSG   2053
#define IDS_STREAM_EMPTY_NAME_TITLE 2054
#define IDS_STREAM_ERR_CREATE    2055
#define IDS_STREAM_NO_FILE_MSG   2056
#define IDS_STREAM_NO_FILE_TITLE 2057
#define IDS_EXIF_COL_NUM         2060
#define IDS_EXIF_COL_TAG         2061
#define IDS_EXIF_COL_TYPE        2062
#define IDS_EXIF_COL_VALUE       2063
#define IDS_EXIF_DASH            2064
#define IDS_EXIF_NO_META_MSG     2065
#define IDS_EXIF_ERR_READ        2066
#define IDS_EXIF_NO_SUPPORT      2067
#define IDS_EXIF_NO_SUPPORT_HINT 2068
#define IDS_STREAM_MENU_DELETE   2070
#define IDS_STREAM_DEL_FMT       2071
#define IDS_STREAM_DEL_TITLE     2072
#define IDS_STREAM_DEL_OK        2073
#define IDS_STREAM_DEL_OK_TITLE  2074
#define IDS_STREAM_VIEW_TITLE    2075
#define IDS_STREAM_MODE_TEXT     2076
#define IDS_STREAM_MODE_HEX      2077
#define IDS_MENU_COPY            2078
#define IDS_EXIF_EDIT_TITLE      2079
#define IDS_EXIF_EDIT_LABEL      2080
#define IDS_EXIF_SAVE_OK         2081
#define IDS_EXIF_SAVE_OK_TITLE   2082
#define IDS_EXIF_SAVE_ERR        2083
#define IDS_EXIF_READONLY        2084
#define IDS_COMPARE_TITLE        2085
#define IDS_COMPARE_RESULT       2086
#define IDS_COMPARE_EQUAL        2087
#define IDS_COMPARE_WITH         2088
#define IDS_RECENT_SEP           2089
#define IDS_ADD_COMPR_FMT        2090
#define IDS_ADD_STORAGE_FMT      2091
#define IDS_ADD_ALIGN_FMT        2092
#define IDS_ADD_REPARSE_FMT      2093
#define IDS_STREAM_VIEWER_CLOSE  2094
#define IDS_SAVE_CONFIRM_MSG     2095
#define IDS_SAVE_CONFIRM_TITLE   2096
#define IDS_STREAM_INVALID_NAME  2097
#define IDS_SIZE_FMT             2098
#define IDC_FILE_OWNER           1092
#define IDC_EXTRA_INFO           1093

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
